// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACpMNjKknMtM3D6_eMEB3UN4wIhIKugNQ',
    appId: '1:335504374053:web:2800a0de550642ce2d42cc',
    messagingSenderId: '335504374053',
    projectId: 'sistema-parkwise',
    authDomain: 'sistema-parkwise.firebaseapp.com',
    storageBucket: 'sistema-parkwise.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA-5XujGtPZI9hxVoFID5aFzLRjXymeIk',
    appId: '1:335504374053:android:39b521ca2cff33992d42cc',
    messagingSenderId: '335504374053',
    projectId: 'sistema-parkwise',
    storageBucket: 'sistema-parkwise.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCppIWb6F2oRVGYiJLSBw0fOgvSz9ZwjkI',
    appId: '1:335504374053:ios:f4034e6f18fed0532d42cc',
    messagingSenderId: '335504374053',
    projectId: 'sistema-parkwise',
    storageBucket: 'sistema-parkwise.firebasestorage.app',
    iosBundleId: 'com.marcacaovagas.marcacaovagas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCppIWb6F2oRVGYiJLSBw0fOgvSz9ZwjkI',
    appId: '1:335504374053:ios:f4034e6f18fed0532d42cc',
    messagingSenderId: '335504374053',
    projectId: 'sistema-parkwise',
    storageBucket: 'sistema-parkwise.firebasestorage.app',
    iosBundleId: 'com.marcacaovagas.marcacaovagas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACpMNjKknMtM3D6_eMEB3UN4wIhIKugNQ',
    appId: '1:335504374053:web:690c18fab94ad2e32d42cc',
    messagingSenderId: '335504374053',
    projectId: 'sistema-parkwise',
    authDomain: 'sistema-parkwise.firebaseapp.com',
    storageBucket: 'sistema-parkwise.firebasestorage.app',
  );

}