// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4NlP32UgFuaJTwnj1bsTy5Sid3mFMrcg',
    appId: '1:780168884512:web:ee66981829b425c80b2745',
    messagingSenderId: '780168884512',
    projectId: 'gestao-vagas',
    authDomain: 'gestao-vagas.firebaseapp.com',
    storageBucket: 'gestao-vagas.firebasestorage.app',
    measurementId: 'G-BB1SZMZGSE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKJapu0KuDwWw2QI_BKtoHT-TXv3BYviY',
    appId: '1:780168884512:android:6ccae1c1989216050b2745',
    messagingSenderId: '780168884512',
    projectId: 'gestao-vagas',
    storageBucket: 'gestao-vagas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW7mdamYgLqeUsjcvQ3u2h0WwGLgvlbcM',
    appId: '1:780168884512:ios:49356c6dabb2acdd0b2745',
    messagingSenderId: '780168884512',
    projectId: 'gestao-vagas',
    storageBucket: 'gestao-vagas.firebasestorage.app',
    iosBundleId: 'com.marcacaovagas.marcacaovagas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW7mdamYgLqeUsjcvQ3u2h0WwGLgvlbcM',
    appId: '1:780168884512:ios:49356c6dabb2acdd0b2745',
    messagingSenderId: '780168884512',
    projectId: 'gestao-vagas',
    storageBucket: 'gestao-vagas.firebasestorage.app',
    iosBundleId: 'com.marcacaovagas.marcacaovagas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4NlP32UgFuaJTwnj1bsTy5Sid3mFMrcg',
    appId: '1:780168884512:web:425c94b2dee59e250b2745',
    messagingSenderId: '780168884512',
    projectId: 'gestao-vagas',
    authDomain: 'gestao-vagas.firebaseapp.com',
    storageBucket: 'gestao-vagas.firebasestorage.app',
    measurementId: 'G-Q8VQTHVNHV',
  );
}
